apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: python
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-mysql
  labels:
    app: python
spec:
  selector:
    matchLabels:
      app: python
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        tier: mysql
    spec:
      containers:
      - image: paulinefd/mariadb
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql    
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

              

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  selector:
    matchLabels:
      app: python 
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - image: paulinefd/python
        name: python
        ports:
        - containerPort: 5000
          name: python  
          
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python-sql
  name: python-sql
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 3306
  selector:
    app: python-sql
  type: NodePort
status:
  loadBalancer: {}          
