pipeline {
 agent any
  stages {
    stage('clone'){
      steps {
        git url: 'https://github.com/JeanHuret/FormationPOEI.git'
      }
    }
    stage('Build'){
      tools {
        gradle 'gradle'
      }
      steps {
        sh 'cd Projet_final/app/app_python && gradle purge'
        sh 'cd Projet_final/app/app_python && gradle dependance'       
      }
    } 
    stage('Rapport qualité'){
      tools {
        gradle 'gradle'
      }
      steps { 
        parallel (
          pylint: {
            sh 'cd Projet_final/app/app_python && gradle lint'
          },
          pycode: {
            sh 'cd Projet_final/app/app_python && gradle pycodestyle'
          }
        )
      }
    }
    stage('Package') {
      tools {
        gradle 'gradle'
      }
      steps {
        sh 'cd Projet_final/app/app_python && gradle packageDistribution'
      }
    }
    stage ('Ansible'){
      steps {
        ansiblePlaybook installation: 'ansible', inventory: 'Projet_final/hosts', playbook: 'Projet_final/playbook.yml'
      }
    }
  }      
  post {
       always{
             post {
          always {
            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'Gradle/test-reports', reportFiles: 'index.html', reportName: 'Flake 8 violations', reportTitles: ''])
            recordIssues(
                    tools: [pep8(pattern: 'Projet_final/app/app_python/test-reports/flake8/result-pycode.report')]
                )
            junit 'Projet_final/app/app_python/test-reports/flake8/*.xml'
          }
      }
    }
  }
}