version: "3.7"

services:
  gradle:
    build: ./
    image: gradle
    container_name: gradle
  jenkins:
    ports: 
      - "8098:8080"
      - "50000:50000"
    image: my_jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
  
  master:
    image: alpine:latest
    container_name: master01
    hostname: master01
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "apk update 
      apk add ansible openssh-server openssh
      /bin/sh"
    volumes:
      - ansible_vol:/var/ans
      - ./files/:/files/
  
  host:
    links:
      - master
    image: ubuntu
    container_name: application
    hostname: application
    stdin_open: true
    tty: true
    command : >
      /bin/sh -c "apt update 
      apt upgrade -y 
      DEBIAN_FRONTEND=noninteractive 
      mkdir -p /run/sshd
      apt install -y apt --no-install-recommends openssh-server python3 
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config      
      echo 'root:toor' | chpasswd 
      /usr/sbin/sshd -D"
    expose: 
      - 22
    volumes:
     - ansible_vol:/var/ans

  dbserver:
      links:
        - master
      image: ubuntu
      container_name: dbserver
      hostname: dbserver
      stdin_open: true
      tty: true
      command : >
        /bin/sh -c "apt update && apt upgrade -y 
        DEBIAN_FRONTEND=noninteractive 
        mkdir /run/sshd 
        apt install -y apt --no-install-recommends python3 openssh-server sudo 
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
        echo 'root:toor' | chpasswd 
        /usr/sbin/sshd -D"
      expose: 
        - 22
      ports:
        - 3306:3306
      volumes:
      - ansible_vol:/var/ans
volumes:
  ansible_vol:
  jenkins_home: {}
